# Generated by Django 5.1.5 on 2025-05-12 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loefusers', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='requires_skippership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loefusers.skippership'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='authorized_skipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_skipper_reservation_set', to='loefusers.userskippership'),
        ),
    ]
